### ISSUE TITLE
CREATE ASSEMBLY fails due to missing signature or different CLR version, this workaround works

### ISSUE THREAD

**Issue by riyazwalikar** [infiniteloopltd/SQLHttp#1]
Needed to add the hash of the assembly to `sys.trusted_assemblies` on `Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)`

Ran the following before `CREATE ASSEMBLY`

```
EXEC sp_add_trusted_assembly 0x35acf108139cdb825538daee61f8b6b07c29d03678a4f6b0a5dae41a2198cf64cefdb1346c38b537480eba426e5f892e8c8c13397d4066d4325bf587d09d0937,N'HttpDb, version=0.0.0.0, culture=neutral, publickeytoken=null, processorarchitecture=msil';
```

**Comment by dlatikaynen** [comment]
After getting it to install successfully with @riyazwalikar 's addition ↑, an actual call fails as follows:

```
SELECT dbo.http('http://icanhazip.com')
```

```
Msg 6522, Level 16, State 1, Line 26
A .NET Framework error occurred during execution of user-defined routine or aggregate "http": 
System.Security.SecurityException: Request for the permission of type 'System.Net.WebPermission, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
System.Security.SecurityException: 
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at UserDefinedFunctions.http(SqlString url)
```

Creating the assembly with PERMISSION_SET = SAFE works but then the call to
```
ALTER ASSEMBLY [HttpDb] WITH PERMISSION_SET = EXTERNAL_ACCESS;
```
fails with another error:
```
Msg 10342, Level 16, State 100, Line 29
Assembly 'HttpDb' cannot be loaded because this edition of SQL Server only supports SAFE assemblies.
```

("this edition" in our case is Microsoft SQL Server 2022 (RTM-CU21) (KB5065865) - 16.0.4215.2 (X64)   Aug 11 2025 13:24:21   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 22.04.5 LTS) <X64>)

Looks like you're out of luck on linux: https://stackoverflow.com/a/59195418/1132334
